### ISSUE TITLE
When I hit `done` while naming the wallet, the dialog closes without saving

### ISSUE THREAD

**Issue by dredd0614** [ademar111190/BitAC#2]
Is this the expected behavior?  If so please ignore.  I figured `done` would save the wallet.

I suggest removing the `done` button entirely unless I'm missing some expected functionality.

**Comment by ademar111190** [comment]
You have the reason, the `done` buttons are only making confusion, I'll remove it. Thank you @dredd0614

**Comment by ademar111190** [comment]
Fixed a396ffea7c003b69ec366e223b25f32e2dae4ca1
